/*
 *  ::718604!
 * 
 * Copyright(C) November 20, 2014 U.S. Food and Drug Administration
 * Authors: Dr. Vahan Simonyan (1), Dr. Raja Mazumder (2), et al
 * Affiliation: Food and Drug Administration (1), George Washington University (2)
 * 
 * All rights Reserved.
 * 
 * The MIT License (MIT)
 * 
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

-- Generated by: qapp -user qapp -db_init_data_domain_sql

START TRANSACTION;

source db_init_data_include.sql;

SET @type_domain = 1954115685;
SET @type_type_id = 1;
SET @type_domian_id = 2;

DELETE FROM UPPerm WHERE objID = @type_domian_id AND domainID = @type_domain;
DELETE FROM UPObjField WHERE objID = @type_domian_id AND domainID = @type_domain;
DELETE FROM UPObj WHERE objID = @type_domian_id AND domainID = @type_domain;

CALL sp_obj_create_v2(@system_group_id, @system_membership, @type_domain, @type_type_id, @type_domain, @type_domian_id, @system_permission, @system_flags);

CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'name\',\'1\',\'domain-id-descr\',NULL,NULL)'), NULL);
CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'title\',\'1\',\'HIVE domain ID specification\',NULL,NULL)'), NULL);
CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'description\',\'1\',\'Object describing a HIVE domain ID recognized on this HIVE installation\',NULL,NULL)'), NULL);
CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'parent\',\'1\',\'type.84\',NULL,NULL)'), NULL);
CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'prefetch\',\'1\',\'1\',NULL,NULL)'), NULL);

CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'field_name\',\'1.1.1\',\'domain-id-descr_ascii\',NULL,NULL)'), NULL);
CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'field_title\',\'1.1.1\',\'Domain ID (ascii)\',NULL,NULL)'), NULL);
CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'field_type\',\'1.1.1\',\'string\',NULL,NULL)'), NULL);
CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'field_is_key_fg\',\'1.1.1\',\'1\',NULL,NULL)'), NULL);
CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'field_description\',\'1.1.1\',\'up to 8 characters in [a-z_] range\',NULL,NULL)'), NULL);

CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'field_name\',\'1.2.1\',\'domain-id-descr_comment\',NULL,NULL)'), NULL);
CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'field_title\',\'1.2.1\',\'Comment\',NULL,NULL)'), NULL);
CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'field_type\',\'1.2.1\',\'text\',NULL,NULL)'), NULL);
CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'field_is_optional_fg\',\'1.2.1\',\'1\',NULL,NULL)'), NULL);

CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'field_name\',\'1.3.1\',\'domain-id-descr_title\',NULL,NULL)'), NULL);
CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'field_title\',\'1.3.1\',\'Title\',NULL,NULL)'), NULL);
CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'field_type\',\'1.3.1\',\'string\',NULL,NULL)'), NULL);
CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'field_order\',\'1.3.1\',\'1\',NULL,NULL)'), NULL);
CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'field_brief\',\'1.3.1\',\'Domain $_(v)\',NULL,NULL)'), NULL);

CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'field_name\',\'1.4.1\',\'domain-id-descr_uri\',NULL,NULL)'), NULL);
CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'field_title\',\'1.4.1\',\'URI\',NULL,NULL)'), NULL);
CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'field_type\',\'1.4.1\',\'string\',NULL,NULL)'), NULL);
CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'field_order\',\'1.4.1\',\'2\',NULL,NULL)'), NULL);
CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'field_is_key_fg\',\'1.4.1\',\'1\',NULL,NULL)'), NULL);
CALL sp_obj_prop_set_v3(@system_group_id, @system_membership, @type_domain, @type_domain_id, @system_permission, CONCAT('(', @type_domain, ',', @type_domain_id, ',\'field_brief\',\'1.4.1\',\'($_(v))\',NULL,NULL)'), NULL);


CALL sp_obj_perm_set_v2(@system_group_id, @system_membership, @system_group_id, @type_domain, @type_domian_id, 0, 0, @system_permission, @system_flags, TRUE);
CALL sp_obj_perm_set_v2(@system_group_id, @system_membership, @everyone_group_id, @type_domain, @type_domian_id, 0, 0, @everyone_permission, @everyone_flags, TRUE);


COMMIT;
