[metadata]
name = fdahivecli
version = 1.1.1
author = FDA HIVE Team
author_email = hive@fda.hhs.gov
description = a library for interacting with HIVE instances that enables users to login, download objects, retrieve information about objects, and upload files.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://dnahive.fda.gov
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
scripts = bin/fdahivecli
python_requires = >=3.6

[options.packages.find]
where = src