/*
 *  ::718604!
 * 
 * Copyright(C) November 20, 2014 U.S. Food and Drug Administration
 * Authors: Dr. Vahan Simonyan (1), Dr. Raja Mazumder (2), et al
 * Affiliation: Food and Drug Administration (1), George Washington University (2)
 * 
 * All rights Reserved.
 * 
 * The MIT License (MIT)
 * 
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

var vFact_array = new Array (
    "HIVE developers have combined 144 years of professional experence in science and technologies.",
    "Did you know that 90% of what you know is made up by people leaving at least 200 years ago and having less than 15% of your intelligence?",
    "Word Science derives from Latin word scientia meaning knowledge.",
    "Human need approximately 12 hours in order to entirely digest the food.",
    "Brain cells are the longest living cells in our body, they can last for an entire lifetime.",
    "Some human brains are bigger than other and the biggest human brain weighed 2,3 kg.",
    "Venus is the hottest planet in our solar system with surface temperature above 450 C.",
    "If we are to believe scientists there are approximately 50,000,000,000 galaxies out there.",
    "Sound travels 4 times faster in water than in air.",
    "One of the most accidental discoveries was the one of microwave. This discovery happened after a researcher walked by a radar tube and a chocolate bar melted in his pocket.",
    "Kissing or shaking hands? In terms of germs be aware that more germs are transferred shaking hands than kissing.",
    "Our moon is extremely dry, it is for instance one million times drier than the infamous Gobi Desert.",
    "Not all animals on our planet have brains, for instance starfish do not have brains.",
    "Kangaroos are lacking ability to walk backwards.",
    "Eyes always remain same in size since the time we are born and till the moment we die, unlike our ears and nose that are constantly growing throughout our life.",
    "Only humans have ability to sleep on their backs.",
    "Our brain isn't much different than the rest of our body in terms of water since 80 % of our brain is water.",
    "Our brain for proper functioning needs about quarter of total oxygen used by our body.",
    "Crocodiles are not only swallowing unlucky victims but also the stones in order to help them dive deeper.",
    "While cancer is perhaps the greatest disease of humanity, sharks do not have this problem as they are totally immune to cancer.",
    "Surprisingly enough little mosquito has 47 teeth.",
    "Ants are so hardworking that they even do not sleep.",
    "In terms of rapid procreation rats lead the way since two rats can have after year and the half more than 1 million descendants.",
    "Our fingernails are growing much faster than our toenails, about 4 times faster.",
    "Talking about the hot stuff - The highest temperature produced in a laboratory was 920,000,000 F (511,000,000 C) at the Tokamak Fusion Test Reactor in Princeton, NJ, USA.",
    "Hurricanes cause havoc which is really no surprise since a typical hurricane produces the energy equivalent to 8,000 one megaton bombs.",
    "Polar bears may look slow and fat, but they are in real life far from it since they can run at 25 miles an hour and jump over 6 feet in the air.",
    "Mosquitoes like women more than men since they very much like smell of estrogen.",
    "In case you have ever wondered why giraffes are such a quiet animals it is because they have no vocal chords to make any noise.",
    "Interesting enough, Earth is the only planet in our solar system that hasn't been named after some Roman or Greek god.",
    "Year is not always longer time period than a day. Mercury for instance has one day on the planet twice as long as one year. This is because Mercury rotates very slowly but revolves around the Sun in slightly less than 88 days.",
    "Our Sun may be gigantic but it still loses 360 million tonnes of material each day.",
    "In case you want to be taller than the perfect profession for you is astronaut since astronauts can be up to 2 inches taller returning from space.This happens because the cartilage disks in the spine expand in the absence of gravity.",
    "In case you ever wonder how much does a gallon of water weighs the answer is 8.34 pounds (3.8kg).",
    "Though many would say otherwise hot water freezes quicker than the cold water.",
    "Albert Einstein had speech difficulties in early age.",
    "Lions are excellent hunters especially when you consider that they usually hunt in coordinated groups and stalk their chosen prey.",
    "Methane is extremely potent greenhouse gas and cows are among the largest methane emitters with each domestic cow emitting about 105 pounds of methane a year.",
    "So far scientists have discovered over 20 planets outside our solar system.",
    "Spacecrafts are extremely fast, with fastest one going to 40,000 mph.",
    "Can you live without you head? Well if you are a cockroach you can manage somewhere around 9 days or so.",
    "So how alike are humans and chimps? Well if you consider that we share 98.4% of our DNA you could say a very lot, though on other hand we do share 70% of our DNA with a slug.",
    "Human fetuses are in fact great fans of rock music since they react to loud rock music by kicking, or does this mean that they hate rock?",
    "Average male brain is larger than average female brain (1,4 kg to 1,25 kg).",
    "Humans are not the only creatures on Earth that cry, elephants are crying creatures too.",
    "Polar bears would make perfect thieves since they cannot be detected by infrared cameras because of their transparent fur.",
    "Rats are really fast lovers, especially desert rats that can copulate 122 times an hour.",
    "Lefties are really in minority since 88% of all humans are right handed.",
    "Smelly feet are likely to get you in more trouble with mosquitoes since they prefer people with smelly feet.",
    "Snails are definitely among the sleepiest animals as they can sleep for three years.",
    "Did you know that there are 206 bones in the adult human body and there are 300 in children (as they grow some of the bones fuse together).",
    "Flea's can jump 130 times higher than their own height. In human terms this is equal to a 6ft. person jumping 780 ft. into the air.",
    "The most dangerous animal in the world is the common housefly. Because of their habits of visiting animal waste, they transmit more diseases than any other animal.",
    "Snakes are true carnivorous because they eat nothing but other animals. They do not eat any type of plant material.",
    "The world's largest amphibian is the giant salamander. It can grow up to 5 ft. in length.",
    "100 years ago: The first virus was found in both plants and animals.",
    "90 years ago: The Grand Canyon became a national monument &amp; Cellophane is invented.",
    "80 years ago: The food mixer and the domestic refrigerator were invented.",
    "70 years ago: The teletype and PVC (polyvinyl-chloride) were invented.",
    "60 years ago: Otto Hahn discovered nuclear fission by splitting uranium, Teflon was invented.",
    "50 years ago: Velcro was invented.",
    "40 years ago: An all-female population of lizards was discovered in Armenia.",
    "30 years ago: The computer mouse was invented.",
    "20 years ago: First test-tube baby born in England, Pluto's moon, Charon, discovered.",
    "10 years ago: First patent for a genetically-engineered mouse was issued to Harvard Medical School.",
    "5 years ago: The first successful cloning of human embryo",
    "The smallest bone in the human body is the stapes or stirrup bone located in the middle ear. It is approximately .11 inches (.28 cm) long.",
    "The longest cells in the human body are the motor neurons. They can be up to 4.5 feet (1.37 meters) long and run from the lower spinal cord to the big toe.",
    "There are no poisonous snakes in Maine.",
    "The blue whale can produce sounds up to 188 decibels. This is the loudest sound produced by a living animal and has been detected as far away as 530 miles.",
    "The largest man-made lake in the U.S. is Lake Mead, created by Hoover Dam.",
    "The poison arrow frogs of South and Central America are the most poisonous animals in the world.",
    "A new born blue whale measures 20-26 feet (6.0 - 7.9 meters) long and weighs up to 6,614 pounds (3003 kg).",
    "The first coast-to-coast telephone line was established in 1914.",
    "The Virginia opossum has a gestation period of only 12-13 days.",
    "The Stegosaurus dinosaur measured up to 30 feet (9.1 meters) long but had a brain the size of a walnut.",
    "The largest meteorite crater in the world is in Winslow, Arizona. It is 4,150 feet across and 150 feet deep.",
    "The human eye blinks an average of 4,200,000 times a year.",
    "Skylab, the first American space station, fell to the earth in thousands of pieces in 1979. Thankfully most over the ocean.",
    "&nbsp;It takes approximately 12 hours for food to entirely digest.",
    "Human jaw muscles can generate a force of 200 pounds (90.8 kilograms) on the molars.",
    "The Skylab astronauts grew 1.5 - 2.25 inches (3.8 - 5.7 centimeters) due to spinal lengthening and straightening as a result of zero gravity.",
    "An inch (2.5 centimeters) of rain water is equivalent to 15 inches (38.1 centimeters) of dry, powdery snow.",
    "Tremendous erosion at the base of Niagara Falls (USA) undermines the shale cliffs and as a result the falls have receded approximately 7 miles over the last 10,000 years.",
    "40 to 50 percent of body heat can be lost through the head (no hat) as a result of its extensive circulatory network.",
    "A large swarm of desert locusts (Schistocerca gregaria) can consume 20,000 tons (18,160,000 kilograms) of vegetation a day.",
    "The largest telescope in the world is currently being constructed in northern Chile. The telescope will utilize four - 26 ft. 8 in. (8.13 meters) mirrors which will gather as much light as a single 52 ft. 6 in. (16 meters) mirror.",
    "The Hubble Space Telescope weighs 12 tons (10,896 kilograms), is 43 feet (13.1 meters) long, and cost $2.1 billion to originally build.",
    "The longest living cells in the body are brain cells which can live an entire lifetime.",
    "&nbsp;The largest flying animal was the pterosaur which lived 70 million years ago. This reptile had a wing span of 36-39 feet (11-11.9 meters) and weighed 190-250 pounds (86-113.5 kilograms).",
    "The Atlantic Giant Squid's eye can be as large as 15.75 inches (40 centimeters) wide.",
    "Armadillos, opossums, and sloth's spend about 80% of their lives sleeping.",
    ", has been found to live in water as deep as 24,881 feet (7,584 meters).",
    "The tentacles of the giant Arctic jellyfish can reach 120 feet (36.6 meters) in length.",
    "The greatest tide change on earth occurs in the Bay of Fundy. The difference between low tide and high tide can be as great as 54 ft. 6 in. (16.6 meters).",
    "The highest temperature produced in a laboratory was 920,000,000 F (511,000,000 C) at the Tokamak Fusion Test Reactor in Princeton, NJ, USA.",
    "The most powerful laser in the world, the Nova laser at Lawrence Livermore National Laboratory, CA, USA, generates a pulse of energy equal to 100,000,000,000,000 watts of power for .000000001 second to a target the size of a grain of sand.",
    "The fastest computer in the world is the CRAY Y-MP C90 supercomputer. It has two gigabytes of central memory and 16 parallel central processor units.",
    "The heaviest human brain ever recorded weighed 5 lb. 1.1 oz. (2.3 kg.).",
    "The deepest part of the ocean is 35,813 feet (10,916 meters) deep and occurs in the Mariana Trench in the Pacific Ocean. At that depth the pressure is 18,000 pounds (9172 kilograms) per square inch.",
    "The largest cave in the world (the Sarawak Chamber in Malaysia) is 2,300 feet (701 meters) long, 980 feet (299 meters) wide, and more than 230 feet (70 meters) high.",
    "The hottest planet in the solar system is Venus, with an estimated surface temperature of 864 F (462 C).",
    "The ears of a cricket are located on the front legs, just below the knee.",
    "The first electronic digital computer (called ENIAC - the Electronic Numerical Integrator and Calculator) was developed in 1946 and contained over 18,000 vacuum tubes.",
    "The leg muscles of a locust are about 1000 times more powerful than an equal weight of human muscle.",
    "The cosmos contains approximately 50,000,000,000 galaxies.",
    "There are between 100,000,000,000 and 1,000,000,000,000 stars in a normal galaxy.",
    "Sound travels about 4 times faster in water than in air.",
    "Scientists have discovered that copper pollution of the atmosphere occurred about 2500 years ago. This was discovered by analyzing ice cores from Greenland. The pollution was attributed to the Romans who used copper for military purposes and to produce coins.",
    "Hydrofluoric acid will dissolve glass.",
    "In a full grown rye plant, the total length of roots may reach 380 miles (613 km).",
    "In a full grown rye plant, the total length of fine root hairs may reach 6600 miles (10,645 km).",
    "A large sunspot can last for about a week.",
    "If you could throw a snowball fast enough, it would totally vaporize when it hit a brick wall.",
    "Boron nitride (BN) is the second hardest substance known to man.",
    "The female Tarantula Hawk wasp paralyzes a large spider with her sting. She then lays her eggs on the motionless body so that her developing young have a fresh supply of spider meat to feed on.",
    "The seeds of an Indian Lotus tree remain viable for 300 to 400 years.",
    "The only letter not appearing on the Periodic Table is the letter “J”.",
    "Velcro was invented by a Swiss guy who was inspired by the way burrs attached to clothing.",
    "Hershey's Kisses are called that because the machine that makes them looks like it's kissing the conveyor belt.",
    "October 10 is National Metric Day.",
    "If you stretch a standard Slinky out flat it measures 87 feet long.",
    "The microwave was invented after a researcher walked by a radar tube and a chocolate bar melted in his pocket.",
    "Super Glue was invented by accident. The researcher was trying to make optical coating materials, and would test their properties by putting them between two prisms and shining light through them. When he tried the cyano-acrylate, he couldn't get the prisms apart.",
    "No matter its size or thickness, no piece of paper can be folded in half more than 7 times.",
    "A car traveling at 80 km/h uses half its fuel to overcome wind resistance.",
    "Knowledge is growing so fast that ninety per cent of what we will know in fifty years time, will be discovered in those fifty years.",
    "According to an old English system of time units, a moment is one and a half minutes.",
    "The typewriter was invented in 1829, and the automatic dishwasher in 1889.",
    "The wristwatch was invented in 1904 by Louis Cartier.",
    "When glass breaks, the cracks move at speeds of up to 3,000 miles per hour.",
    "By raising your legs slowly and laying on your back, you can't sink in quicksand.",
    "Ten minutes of one hurricane contains enough energy to match the nuclear stockpiles of the world.",
    "Most gemstones contain several elements. The exception? The diamond. It's all carbon.",
    "Diamonds are the hardest substance known to man.",
    "Which of the 50 states has never had an earthquake? North Dakota.",
    "When hydrogen burns in the air, water is formed.",
    "Sterling silver contains 7.5% copper.",
    "Cars were first made with ignition keys in 1949.",
    "J.B Dunlop was first to put air into tires.",
    "Alexander Graham Bell, who invented the telephone, also set a world water-speed record of over seventy miles an hour at the age of seventy two.",
    "It is energy-efficient to turn off a fluorescent light only if it will not be used again within an hour or more. This is because of the high voltage needed to turn it on, and the shortened life this high voltage causes.",
    "The Earth's equatorial circumference (40,075 km) is greater than its polar circumference (40,008 km).",
    "Lake Baikal is the deepest lake in the world.",
    "Due to gravitational effects, you weigh slightly less when the moon is directly overhead.",
    "The Earth's average velocity orbiting the sun is 107,220 km per hour.",
    "There is a high and low tide because of our moon and the Sun.",
    "The United States consumes 25% of all the world's energy.",
    "Flying from London to New York by Concord, due to the time zones crossed, you can arrive 2 hours before you leave.",
    "There is enough fuel in a full tank of a Jumbo Jet to drive an average car four times around the world.",
    "The surface speed record on the moon is 10.56 miles per hour. It was set with the lunar rover.",
    "If you could drive to the sun -- at 55 miles per hour -- it would take about 193 years",
    "The moon is one million times drier than the Gobi Desert.",
    "Just twenty seconds worth of fuel remained when Apollo 11's lunar module landed on the moon.",
    "A Boeing 707 uses four thousand gallons of fuel in its take-off climb.",
    "The planet Saturn has a density lower than water. So, if placed in water it would float.",
    "Since 1959, more than 6,000 pieces of 'space junk' (abandoned rocket and satellite parts) have fallen out of orbit - many of these have hit the earth's surface.",
    "It takes 70% less energy to produce a ton of paper from recycled paper than from trees.",
    "Every year in the US, 625 people are struck by lightning.",
    "Hawaii is moving toward Japan 4 inches every year.",
    "The rocket engine has to supply its own oxygen so it can burn its fuel in outer space.",
    "The North Atlantic gets 1 inch wider every year.",
    "Oxygen is the most abundant element in the Earth's crust, waters, and atmosphere (about 49.5%)",
    "A stroke of lightning discharges from 10 to 100 million volts &amp; 30,000 amperes of electricity.",
    "A bolt of lightning is about 54,000°F (30,000°C); six times hotter than the Sun.",
    "Hydrogen is the most abundant element in the Universe (75%).",
    "The average distance between the Earth &amp; the Moon is 238,857 miles (384,392 km).&nbsp;",
    "The moon is 27% the size of the Earth.",
    "The Earth weighs 6.6 sextillion tons, or 5.97 x 1024 kg.",
    "The center of the Sun is about 27 million degrees Fahrenheit (15 million C).",
    "Sunlight takes about 8 minutes &amp; 20 seconds to reach the Earth at 186,282 miles/sec (299,792 Km/sec).",
    "The highest temperature on Earth was 136 F (5°C) in Libya in 1922.",
    "The lowest temperature on Earth was -128.6 F (-89.6 C) in Antarctica in 1983.",
    "Sunlight can penetrate clean ocean water to a depth of 240 feet.",
    "The average ocean floor is 12,000 feet.",
    "The temperature can be determined by counting the number of cricket chirps in fourteen seconds and adding 40.",
    "House flies have a lifespan of two weeks.",
    "Chimps are the only animals that can recognize themselves in a mirror.",
    "Starfish don't have brains.",
    "The average person falls asleep in seven minutes.",
    "Shrimp's hearts are in their heads.",
    "Every time you lick a stamp, you're consuming 1/10 of a calorie.",
    "The longest recorded flight of a chicken is thirteen seconds",
    "Emus and kangaroos cannot walk backwards.",
    "Cats have over one hundred vocal sounds, while dogs only have about ten.&nbsp;",
    "Porcupines float in water.",
    "An ostrich's eye is bigger that its brain.&nbsp;",
    "An iguana can stay under water for twenty-eight minutes.",
    "The common goldfish is the only animal that can see both infra-red and ultra-violet light.",
    "It's impossible to sneeze with your eyes open.",
    "The pupil of an octopus' eye is rectangular.",
    "Our eyes are always the same size from birth, but our nose and ears never stop growing.",
    "The leg bones of a bat are so thin that no bat can walk.",
    "Ants cannot chew their food, they move their jaws sideways, like scissors, to extract the juices from the food.",
    "Hummingbirds are the only animals able to fly backwards.",
    "A cat has 32 muscles in each ear.",
    "Tigers have striped skin, not just striped fur.",
    "A cat's jaws cannot move sideways.",
    "Armadillos get an average of 18.5 hours of sleep per day.",
    "Armadillos can walk underwater.",
    "There are more beetles than any other kind of creature in the world.",
    "Certain frogs that can survive the experience of being frozen.&nbsp;",
    "Only humans sleep on their backs.",
    "The human brain is 80% water.",
    "Everyone's tongue print is different.",
    "As an adult, you have more than 20 square feet of skin on your body--about the same square footage as a blanket for a queen-sized bed.",
    "In your lifetime, you'll shed over 40 pounds of skin.",
    "15 million blood cells are produced and destroyed in the human body every second.",
    "Every minute, 30-40,000 dead skin cells fall from your body.",
    "The brain uses more than 25% of the oxygen used by the human body.",
    "If your mouth was completely dry, you would not be able to distinguish the taste of anything.",
    "There are more living organisms on the skin of a single human being than there are human beings on the surface of the earth.",
    "Muscles are made up of bundles from about 5 in the eyelid to about 200 in the buttock muscle.",
    "Muscles in the human body (640 in total) make up about half of the body weight.",
    "The human body has enough fat to produce 7 bars of soap.",
    "The human head is a quarter of our total length at birth, but only an eighth of our total length by the time we reach adulthood.",
    "Most people blink about 17,000 times a day.",
    "Moths have no stomach.",
    "Hummingbirds can't walk.",
    "Sea otters have 2 coats of fur.",
    "A starfish can turn its stomach inside out.",
    "A zebra is white with black stripes.",
    "The animal with the largest brain in relation to its body is the ant.",
    "The largest eggs in the world are laid by a shark.",
    "A crocodile's tongue is attached to the roof of its mouth.",
    "Crocodiles swallow stones to help them dive deeper.",
    "Giraffes are unable to cough.",
    "Sharks are immune to cancer.",
    "Despite the hump, a camel's spine is straight.",
    "heetah's can accelerate from 0 to 70 km/h in 3 seconds.",
    "A giraffe's neck contains the same number of vertebrae as a human.",
    "The heart of giraffe is two feet long, and can weigh as much as twenty four pounds.",
    "On average, Elephants sleep for about 2 hours per day.",
    "Lobsters have blue blood.",
    "Shark's teeth are literally as hard as steel.",
    "A mosquito has 47 teeth.",
    "Oxygen, carbon, hydrogen and nitrogen make up 90% of the human body.",
    "Seventy percent of the dust in your home consists of shed human skin",
    "Fish are the only vertebrates that outnumber birds.",
    "A cockroach can live for several weeks without its head.",
    "The average human produces a quart of saliva a day -- about 10,000 gallons in a lifetime",
    "Elephants have been known to remain standing after they die.",
    "The embryos of tiger sharks fight each other while in their mother's womb, the survivor being the baby shark that is born.",
    "Ants do not sleep.",
    "Nearly a third of all bottled drinking water purchased in the US is contaminated with bacteria.",
    "Rats multiply so quickly that in 18 months, two rats could have over 1 million descendents.",
    "An Astronaut can be up to 2 inches taller returning from space. The cartilage disks in the spine expand in the absence of gravity.",
    "The oldest known fossil is of a single-celled organism, blue-green algae, found in 3.2 billion year-old stones in South Africa.",
    "The oldest multicellular fossils date from ~700 million years ago.",
    "The earliest cockroach fossils are about 280 million years old.",
    "Healthy nails grow about 2 cm each year. Fingernails grow four times as fast as toenails.",
    "20/20 vision means the eye can see normally at 20 feet. 20/15 is better; the eye can see at 20 feet what another eye sees at 15 feet.",
    "The average person has 100,000 hairs on his/her head. Each hair grows about 5 inches (12.7 cm) every year.",
    "There are 60,000 miles (97,000 km) in blood vessels in every human.",
    "The speed of light is generally rounded down to 186,000 miles per second. In exact terms it is 299,792,458 m/s (equal to 186,287.49 miles per second).",
    "It takes 8 minutes 17 seconds for light to travel from the Sun's surface to the Earth.",
    "10 percent of all human beings ever born are alive at this very moment.",
    "The Earth spins at 1,000 mph but it travels through space at an incredible 67,000 mph.",
    "Every year, over one million earthquakes shake the Earth.",
    "When Krakatoa erupted in 1883, its force was so great it could be heard 4,800 kilometers away in Australia.",
    "Every second around 100 lightning bolts strike the Earth.",
    "Every year lightning kills 1000 people.",
    "In October 1999 an Iceberg the size of London broke free from the Antarctic ice shelf .",
    "If you could drive your car straight up you would arrive in space in just over an hour.",
    "Human tapeworms can grow up to 22.9m.",
    "The Earth is 4.56 billion years old – the same age as the Moon and the Sun.",
    "The dinosaurs became extinct before the Rockies or the Alps were formed.",
    "Female black widow spiders eat their males after mating.",
    "When a flea jumps, the rate of acceleration is 20 times that of the space shuttle during launch.",
    "If our Sun were just inch in diameter, the nearest star would be 445 miles away.",
    "Astronauts cannot belch – there is no gravity to separate liquid from gas in their stomachs.",
    "The air at the summit of Mount Everest, 29,029 feet is only a third as thick as the air at sea level.",
    "One million, million, million, million, millionth of a second after the Big Bang the Universe was the size of a pea.",
    "DNA was first discovered in 1869 by Swiss Friedrich Mieschler.",
    "The molecular structure of DNA was first determined by Watson and Crick in 1953.",
    "The first synthetic human chromosome was constructed by US scientists in 1997.",
    "The thermometer was invented in 1607 by Galileo.",
    "Alfred Nobel invented dynamite in 1866.",
    "Wilhelm Rontgen won the first Nobel Prize for physics for discovering X-rays in 1895.",
    "The tallest tree ever was an Australian eucalyptus - In 1872 it was measured at 435 feet tall.",
    "Christian Barnard performed the first heart transplant in 1967 – the patient lived for 18 days.",
    "An electric eel can produce a shock of up to 650 volts.",
    "‘Wireless’ communications took a giant leap forward in 1962 with the launch of Telstar, the first satellite capable of relaying telephone and satellite TV signals.",
    "The Ebola virus kills 4 out of every 5 humans it infects.",
    "In 5 billion years the Sun will run out of fuel and turn into a Red Giant.",
    "Giraffes often sleep for only 20 minutes in any 24 hours. They may sleep up to 2 hours (in spurts – not all at once), but this is rare. They never lie down.",
    "There are 60,000 miles of blood vessels in the human body.",
    "An individual blood cell takes about 60 seconds to make a complete circuit of the body.",
    "On the day that Alexander Graham Bell was buried the entire US telephone system was shut down for 1 minute in tribute.",
    "The low frequency call of the humpback whale is the loudest noise made by a living creature.",
    "A quarter of the world's plants are threatened with extinction by the year 2010.",
    "Each person sheds 40lbs of skin in his or her lifetime.",
    "At 15 inches the eyes of giant squids are the largest on the planet.",
    "The Universe contains over 100 billion galaxies.",
    "Wounds infested with maggots heal quickly and without spread of gangrene or other infection.",
    "More germs are transferred shaking hands than kissing.",
    "The fastest speed a falling raindrop can hit you is 18mph.",
    "It would take over an hour for a heavy object to sink 6.7 miles down to the deepest part of the ocean.",
    "Around a million, billion neutrinos from the Sun will pass through your body while you read this sentence.",
    "The deepest part of any ocean in the world is the Mariana trench in the Pacific with a depth of 35,797 feet.",
    "Every hour the Universe expands by a billion miles in all directions.",
    "Somewhere in the flicker of a badly tuned TV set is the background radiation from the Big Bang.",
    "Even traveling at the speed of light it would take 2 million years to reach the nearest large galaxy, Andromeda.",
    "A thimbleful of a neutron star would weigh over 100 million tons.",
    "Did you know that the HIVE developer team speaks 21 languages?",
    "Did you know that the HIVE developer team speaks 21 languages?",
    ""
 );

 var gFact_delay=30000;

 function vFact_Progress(objname, delay, repeat)
 {

    var  o=gObject(objname);
    if(!o)return;
    //if(repeat && o.innerHTML.indexOf("<vFact>")!=0)return ;

    if(!delay) delay=gFact_delay;

    var r=parseInt( Math.random()*(vFact_array.length-1) ) ;

    var ttt="";//"<vFact>";
    ttt+=vFact_array[r];
    /*
    ttt="<table border=0 width=600>";
        ttt+="<tr>";
            ttt+="<td valign=center>";
                ttt+="<img border=0 src='img/unknown.png' />";
            ttt+="</td>";
            ttt+="<td valign=center>";
                ttt+="<span class='HIVE_fact'>"+vFact_array[r]+"</span>";
                ttt+="<br/><br/><br/><br/><br/>";
                ttt+="<span class='HIVE_descr'>BTW: you have only about " + parseInt(delay/1000)+",000,000,000,000 pico-seconds to conceptualize this.</span>";
            ttt+="</td>";
        ttt+="</tr>";
    ttt+="</table>";
    */
    o.innerHTML=ttt;
    setTimeout("vFact_Progress('"+objname+"', "+delay+",1)",delay);

 }


//http://www.universal-web-design.com/vectors-arrows-04.aspx

//# sourceURL = getBaseUrl() + "/js/facts.js"